### ISSUE TITLE
Security check: Sorry, we need additional information to verify your identity.

### ISSUE THREAD

**Issue by aldrinlambon** [microsoft/Hack-Together-Fabric-AI#6]
I've tried following the steps in [https://aka.ms/upgrade-to-fabric](https://aka.ms/upgrade-to-fabric) to get trial access for the hackathon. I've already tried several phone numbers with my country code, however the prompt is still the same "Sorry, we need additional information to verify your identity". Is the trial steps only available to you US-based participants?

**Comment by toolboc** [comment]
Fabric trials are not geo-restricted to my knowledge, what country code is giving you this issue?

**Comment by aldrinlambon** [comment]
+63 Philippines is the country code I'm using. Is there another work around to get trial access?

**Comment by toolboc** [comment]
@aldrinlambon, unfortunately this appears to a longstanding issue related to Office E5 trial activation (required in order to proceed to Microsoft Fabric Trial activation) that goes back at least a couple years with no known workaround (aside using a valid number from one of the avaialble countries in the Office E5 trial activation steps).  More details here: https://answers.microsoft.com/en-us/msoffice/forum/all/setup-e5-subscription-ms-dev-program-country-not/bea465c8-4c21-4eef-8f59-9ca6b0884843

I will try to see if I can find additional information internally, but this very well may be a blocker.

**Comment by aldrinlambon** [comment]
Oh that's unfortunate. I already have necessary resources for my submission and only the blocker is having the a trial access for the development. 

@toolboc Hope you can find some sort of workaround internally. I was really looking forward in participating in this hackathon..

**Comment by toolboc** [comment]
@aldrinlambon, let’s take this conversation over to LinkedIn (https://www.linkedin.com/in/pjdecarlo), I think I have a solution for you :)
